## Basic Configuration

baseurl = "https://cimentadaj.github.io/"
builddrafts = false
canonifyURLs = true
relativeurls = false
languageCode = "en-US"
contentdir = "content"
layoutdir = "layouts"
publishdir = "public"

author = "Jorge Cimentada"
title = "Jorge Cimentada"
theme = "hugo-goa"
RSSLink = true

## Hugo Built-in Features
disqusShortname = "cimentadaj-github-io" # Comment out to disable Disqus.
googleAnalytics = "XYZ"
enableRobotsTXT = true

[permalinks]
    post = "/:year/:month/:day/:slug/"

## Site Settings
[params]
author = "Jorge Cimentada"
intro = "Sociology/R/Statistics"

# Ignored description but this goes under the intro in the
# root website
description = ""

highlightjsVersion = "9.11.0"
highlightjsCDN = "//cdn.bootcss.com"
highlightjsLang = ["r", "yaml", "tex"]
highlightjsTheme = "github"
MathJaxCDN = "//cdn.bootcss.com"
MathJaxVersion = "2.7.1"


authorimage = "headshot.jpg"
dateformat = "Jan 2, 2006"

## Site Meta Settings
[params.meta]
description = "Simple minimalist theme"
keywords = "blog,goa,hugo,r,statistics,education"

## Social Accounts
[params.social]
github = "cimentadaj"
# instagram = "<username>"
# xing = "<username>"
linkedin = "jorge-cimentada-1740877a/"
twitter = "cimentadaj"
stackoverflow = "3617958/cimentadaj"
email = "cimentadaj@gmail.com"

# Trying to add ORCID following this example:
# https://ab604.github.io/docs/website_bookdown/adding-content-to-the-site.html
# [[params.social]]
#     icon = "github"
#     icon_pack = "ai"
#     link = "cimentadaj"

# [[params.social]]
#     icon = "linkedin"
#     icon_pack = "fa"
#     link = "jorge-cimentada-1740877a/"

# [[params.social]]
#     icon = "twitter"
#     icon_pack = "fa"
#     link = "cimentadaj"

# [[params.social]]
#     icon = "envelope"
#     icon_pack = "fa"
#     link = "cimentadaj@gmail.com"

# [[params.social]]
#     icon = "orcid"
#     icon_pack = "ai"
#     link = "https://orcid.org/0000-0001-5594-1156"

## Extras
[params.extra]
copyright = "© 2017. Jorge Cimentada. [Some Rights Reserved](http://creativecommons.org/licenses/by/3.0/)."
poweredby = true
highlightjs = true

ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

## Main Menu
## weight sets the order in the menu
[[menu.main]]
    name = "blog"
    weight = 1
    identifier = "blog"
    url = "/blog/"
[[menu.main]]
    name = "about"
    identifier = "about"
    weight = 2
    url = "/about/"
[[menu.main]]
    name = "projects"
    identifier = "projects"
    weight = 3
    url = "/projects/"
[[menu.main]]
    name = "vitae"
    identifier = "vitae"
    weight = 4
    url = "/vitae/"
